dist: trusty
sudo: false
group: beta

language: node_js
node_js:
- node
addons:
  firefox: '49.0.2'
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- "[ x$(cat node_modules/.last-node-version 2>/dev/null) = x$(node -e 'console.log(process.version)') ] || (npm rebuild && node -e 'console.log(process.version)' > node_modules/.last-node-version)"
before_script:
- npm install bower@1.8.2 polylint polymer-cli
- $(npm bin)/bower install
- $(npm bin)/polylint --no-recursion
script:
- $(npm bin)/polymer test